"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

import {
  canCreateFromParsedCommand,
  ledgerStatusForConfidence,
  type ParsedFinanceCommand,
} from "@finance/contracts";
import { Icon } from "@/components/ui/icon";
import {
  createLedgerEntry,
  money,
  type LedgerOptions,
} from "@/lib/api";

export function CommandProposal({
  result,
  options,
  note,
  inputMethod,
  inputSessionId,
  onDiscard,
  onSaved,
}: {
  result: ParsedFinanceCommand;
  options: LedgerOptions | null;
  note?: string;
  inputMethod: "text" | "voice";
  inputSessionId?: string;
  onDiscard: () => void;
  onSaved: (message: string) => void;
}) {
  const [accountId, setAccountId] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const suggestedAccountId = useMemo(() => {
    if (!options) return "";
    const matchedAccount = options.accounts.find(
      (account) =>
        account.name.toLowerCase() === result.data.account?.toLowerCase(),
    );
    return matchedAccount?.id || options.accounts[0]?.id || "";
  }, [options, result.data.account]);

  const suggestedCategoryId = useMemo(() => {
    if (!options) return "";
    const matchedCategory = options.categories.find(
      (category) =>
        category.name.toLowerCase() === result.data.category?.toLowerCase(),
    );
    return matchedCategory?.id || options.categories[0]?.id || "";
  }, [options, result.data.category]);

  const selectedAccountId = accountId || suggestedAccountId;
  const selectedCategoryId = categoryId || suggestedCategoryId;
  const canCreate = canCreateFromParsedCommand(result.confidence);
  const status = ledgerStatusForConfidence(result.confidence);

  const handleConfirmSave = async () => {
    if (!selectedAccountId || !selectedCategoryId || saving || !canCreate) {
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const dateStr =
        result.data.occurredAt || new Date().toISOString().slice(0, 10);
      await createLedgerEntry({
        type: result.data.type,
        amount: result.data.amount,
        currency: result.data.currency || "USD",
        merchant: result.data.merchant || undefined,
        accountId: selectedAccountId,
        categoryId: selectedCategoryId,
        occurredAt: `${dateStr}T12:00:00.000Z`,
        note: note?.trim() || undefined,
        inputMethod,
        confidence: result.confidence,
        status,
        inputSessionId,
      });
      onSaved(
        status === "needs_review"
          ? "Saved to your review inbox. Confirm it there before it posts to the ledger."
          : "Entry saved to your ledger successfully!",
      );
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to save entry to ledger",
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <section className="surface-card border-action/30 grid gap-6 p-5 sm:p-6">
      <div className="flex items-start gap-3">
        <span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-action-soft text-action">
          <Icon name="sparkles" />
        </span>
        <div className="w-full">
          <div className="flex items-center justify-between gap-3">
            <p className="font-semibold text-ink">Parsed Command Proposal</p>
            <span className="rounded-full bg-action-soft px-2.5 py-0.5 text-xs font-semibold text-action">
              {(result.confidence * 100).toFixed(0)}% confidence
            </span>
          </div>
          <p className="mt-1 text-sm leading-6 text-muted">
            Structured proposal generated by AI. Review parameters below and
            confirm to save to the database.
          </p>
          {!canCreate ? (
            <p className="mt-3 rounded-lg bg-danger-soft/60 px-3 py-2 text-sm text-danger">
              Confidence is too low to create a ledger entry. Edit the source
              and try again, or discard this proposal.
            </p>
          ) : status === "needs_review" ? (
            <p className="mt-3 rounded-lg bg-review-soft px-3 py-2 text-sm text-review">
              This will be saved to the review inbox instead of posting
              immediately.
            </p>
          ) : null}
          <div className="mt-4 grid gap-3 sm:grid-cols-4">
            <Detail label="Amount" value={money(result.data.amount)} />
            <Detail label="Type" value={result.data.type} />
            <Detail label="Category" value={result.data.category} />
            <Detail label="Account" value={result.data.account} />
            {result.data.merchant ? (
              <Detail label="Merchant" value={result.data.merchant} />
            ) : null}
            <Detail label="Date" value={result.data.occurredAt} />
            <Detail label="Intent" value={result.intent} />
            <Detail label="Currency" value={result.data.currency} />
          </div>
        </div>
      </div>
      {error ? <p className="text-sm text-danger">{error}</p> : null}
      <div className="grid gap-4 border-t border-border pt-5">
        <h3 className="text-sm font-semibold text-ink">
          Confirm account and category
        </h3>
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="text-xs font-medium text-muted">
            Account
            <select
              className="field mt-1"
              onChange={(event) => setAccountId(event.target.value)}
              value={selectedAccountId}
            >
              {options?.accounts.map((account) => (
                <option key={account.id} value={account.id}>
                  {account.name}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs font-medium text-muted">
            Category
            <select
              className="field mt-1"
              onChange={(event) => setCategoryId(event.target.value)}
              value={selectedCategoryId}
            >
              {options?.categories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </label>
        </div>
        <div className="flex justify-end gap-3 pt-2">
          <button
            className="button-secondary text-xs"
            onClick={onDiscard}
            type="button"
          >
            Discard proposal
          </button>
          <button
            className="button-primary text-xs"
            disabled={
              saving || !selectedAccountId || !selectedCategoryId || !canCreate
            }
            onClick={() => void handleConfirmSave()}
            type="button"
          >
            {saving
              ? "Saving…"
              : status === "needs_review"
                ? "Send to review inbox"
                : "Save entry to Ledger"}
          </button>
        </div>
        {status === "needs_review" ? (
          <p className="text-right text-xs text-muted">
            After saving, open the{" "}
            <Link className="font-semibold text-action" href="/review">
              review inbox
            </Link>
            .
          </p>
        ) : null}
      </div>
    </section>
  );
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl bg-surface-muted px-4 py-3">
      <p className="text-xs font-semibold uppercase tracking-wide text-muted">
        {label}
      </p>
      <p className="mt-1 text-sm font-semibold text-ink">{value}</p>
    </div>
  );
}
