"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

import {
  canCreateFromParsedCommand,
  ledgerStatusForConfidence,
  type ParsedFinanceCommand,
} from "@finance/contracts";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Icon } from "@/components/ui/icon";
import { Input } from "@/components/ui/input";
import { createLedgerEntry, money, type LedgerOptions } from "@/lib/api";
import { nativeSelectClassName } from "@/lib/utils";

export function CommandProposal({
  result,
  options,
  note,
  inputMethod,
  inputSessionId,
  onDiscard,
  onSaved,
}: {
  result: ParsedFinanceCommand;
  options: LedgerOptions | null;
  note?: string;
  inputMethod: "text" | "voice" | "receipt";
  inputSessionId?: string;
  onDiscard: () => void;
  onSaved: (message: string) => void;
}) {
  const [accountId, setAccountId] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [merchant, setMerchant] = useState(result.data.merchant ?? "");
  const [amount, setAmount] = useState(String(result.data.amount));
  const [occurredAt, setOccurredAt] = useState(result.data.occurredAt);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const suggestedAccountId = useMemo(() => {
    if (!options) return "";
    const matchedAccount = options.accounts.find(
      (account) =>
        account.name.toLowerCase() === result.data.account?.toLowerCase(),
    );
    return matchedAccount?.id || options.accounts[0]?.id || "";
  }, [options, result.data.account]);

  const suggestedCategoryId = useMemo(() => {
    if (!options) return "";
    const matchedCategory = options.categories.find(
      (category) =>
        category.name.toLowerCase() === result.data.category?.toLowerCase(),
    );
    return matchedCategory?.id || options.categories[0]?.id || "";
  }, [options, result.data.category]);

  const selectedAccountId = accountId || suggestedAccountId;
  const selectedCategoryId = categoryId || suggestedCategoryId;
  const canCreate = canCreateFromParsedCommand(result.confidence);
  const status = ledgerStatusForConfidence(result.confidence);

  const handleConfirmSave = async () => {
    if (!selectedAccountId || !selectedCategoryId || saving || !canCreate) {
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const parsedAmount = Number(amount);
      if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) {
        setError("Enter a positive amount before saving.");
        setSaving(false);
        return;
      }
      const dateStr =
        occurredAt || new Date().toISOString().slice(0, 10);
      await createLedgerEntry({
        type: result.data.type,
        amount: parsedAmount,
        currency: result.data.currency || "USD",
        merchant: merchant.trim() || undefined,
        accountId: selectedAccountId,
        categoryId: selectedCategoryId,
        occurredAt: `${dateStr}T12:00:00.000Z`,
        note: note?.trim() || undefined,
        inputMethod,
        confidence: result.confidence,
        status,
        inputSessionId,
      });
      onSaved(
        status === "needs_review"
          ? "Saved to your review inbox. Confirm it there before it posts to the ledger."
          : "Entry saved to your ledger successfully!",
      );
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to save entry to ledger",
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <Card className="grid gap-6 border-action/30 p-5 sm:p-6">
      <div className="flex items-start gap-3">
        <span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-action-soft text-action">
          <Icon name="sparkles" />
        </span>
        <div className="w-full">
          <div className="flex items-center justify-between gap-3">
            <p className="font-semibold text-ink">Parsed Command Proposal</p>
            <Badge>{(result.confidence * 100).toFixed(0)}% confidence</Badge>
          </div>
          <p className="mt-1 text-sm leading-6 text-muted">
            Structured proposal generated by AI. Review parameters below and
            confirm to save to the database.
          </p>
          {!canCreate ? (
            <p className="mt-3 rounded-lg bg-danger-soft/60 px-3 py-2 text-sm text-danger">
              Confidence is too low to create a ledger entry. Edit the source
              and try again, or discard this proposal.
            </p>
          ) : status === "needs_review" ? (
            <p className="mt-3 rounded-lg bg-review-soft px-3 py-2 text-sm text-review">
              This will be saved to the review inbox instead of posting
              immediately.
            </p>
          ) : null}
          <div className="mt-4 grid gap-3 sm:grid-cols-4">
            <Detail label="Amount" value={money(Number(amount) || 0)} />
            <Detail label="Type" value={result.data.type} />
            <Detail label="Category" value={result.data.category} />
            <Detail label="Account" value={result.data.account} />
            {merchant ? <Detail label="Merchant" value={merchant} /> : null}
            <Detail label="Date" value={occurredAt} />
            <Detail label="Intent" value={result.intent} />
            <Detail label="Currency" value={result.data.currency} />
          </div>
          {result.merchantNormalization ? (
            <p className="mt-3 rounded-lg bg-action-soft px-3 py-2 text-sm text-action">
              Merchant normalized from{" "}
              <strong>{result.merchantNormalization.original}</strong> to{" "}
              <strong>{result.merchantNormalization.canonical}</strong>.
            </p>
          ) : null}
          {result.appliedRules?.length ? (
            <ul className="mt-3 grid gap-2">
              {result.appliedRules.map((rule) => (
                <li
                  className="rounded-lg bg-success-soft/60 px-3 py-2 text-sm text-ink"
                  key={rule.ruleId}
                >
                  {rule.explanation}
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      </div>
      {error ? <p className="text-sm text-danger">{error}</p> : null}
      <div className="grid gap-4 border-t border-border pt-5">
        <h3 className="text-sm font-semibold text-ink">
          {inputMethod === "receipt"
            ? "Correct extracted facts"
            : "Confirm account and category"}
        </h3>
        {inputMethod === "receipt" ? (
          <div className="grid gap-3 sm:grid-cols-3">
            <label className="text-xs font-medium text-muted">
              Merchant
              <Input
                className="mt-1"
                onChange={(event) => setMerchant(event.target.value)}
                value={merchant}
              />
            </label>
            <label className="text-xs font-medium text-muted">
              Amount
              <Input
                className="mt-1"
                inputMode="decimal"
                min="0.01"
                onChange={(event) => setAmount(event.target.value)}
                step="0.01"
                type="number"
                value={amount}
              />
            </label>
            <label className="text-xs font-medium text-muted">
              Date
              <Input
                className="mt-1"
                onChange={(event) => setOccurredAt(event.target.value)}
                type="date"
                value={occurredAt}
              />
            </label>
          </div>
        ) : null}
        <div className="grid gap-3 sm:grid-cols-2">
          <label className="text-xs font-medium text-muted">
            Account
            <select
              className={`${nativeSelectClassName} mt-1`}
              onChange={(event) => setAccountId(event.target.value)}
              value={selectedAccountId}
            >
              {options?.accounts.map((account) => (
                <option key={account.id} value={account.id}>
                  {account.name}
                </option>
              ))}
            </select>
          </label>
          <label className="text-xs font-medium text-muted">
            Category
            <select
              className={`${nativeSelectClassName} mt-1`}
              onChange={(event) => setCategoryId(event.target.value)}
              value={selectedCategoryId}
            >
              {options?.categories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </label>
        </div>
        <div className="flex justify-end gap-3 pt-2">
          <Button
            onClick={onDiscard}
            size="sm"
            type="button"
            variant="secondary"
          >
            Discard proposal
          </Button>
          <Button
            disabled={
              saving || !selectedAccountId || !selectedCategoryId || !canCreate
            }
            onClick={() => void handleConfirmSave()}
            size="sm"
            type="button"
          >
            {saving
              ? "Saving…"
              : status === "needs_review"
                ? "Send to review inbox"
                : "Save entry to Ledger"}
          </Button>
        </div>
        {status === "needs_review" ? (
          <p className="text-right text-xs text-muted">
            After saving, open the{" "}
            <Link className="font-semibold text-action" href="/review">
              review inbox
            </Link>
            .
          </p>
        ) : null}
      </div>
    </Card>
  );
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl bg-surface-muted px-4 py-3">
      <p className="text-xs font-semibold uppercase tracking-wide text-muted">
        {label}
      </p>
      <p className="mt-1 text-sm font-semibold text-ink">{value}</p>
    </div>
  );
}
